alter session set "_oracle_script"=true;

create user user_admin IDENTIFIED BY "123456" DEFAULT TABLESPACE users QUOTA UNLIMITED on users;
create user user_student IDENTIFIED BY "654321" DEFAULT TABLESPACE users QUOTA UNLIMITED on users;

grant RESOURCE, CONNECT, CREATE TABLE, CREATE SESSION TO uSser_admin;
grant RESOURCE, CONNECT, CREATE SESSION TO user_student;

create table my_users (
   ident number not null,
   email varchar2(100 byte) not null,
   username varchar2(50 byte) not null,
   rol varchar2(10 byte) not null,
   passwd varchar2(100 byte) not null,
   constraint my_users_pk primary key (ident),
   constraint my_users_chk1 check (rol in ('BASE', 'ADMIN')),
   constraint my_users_email check (email like '%@%.%'),
   constraint my_users_uk1 unique (email)
);

INSERT INTO my_users VALUES (1901138,'wafae.hamdaoui@gmail.com','user_student','BASE','123456789');
INSERT INTO my_users VALUES (1801140,'meryem.mouhtadi@gmail.com','user_admint','ADMIN','987654321');

CREATE TABLE Ressource (
  id_resource number(15) primary key NOT NULL,
  name_resource varchar(50) NOT NULL,
  location_resource varchar(20) NOT NULL
);

drop table Demandes
CREATE TABLE Demandes (
   ider number GENERATED BY DEFAULT ON NULL AS IDENTITY,
   matricul number not null,
   student varchar2(50) not null,
   ressource varchar2(50) not null,
   duree varchar2(10) not null,
   datee varchar2(10) not null,
   status varchar2(10) not null,
   constraint pk primary key (ider),
   constraint chk0 check (status in ('Waiting','Validated','Rejected')),
   constraint chk1 check (duree in ('09-10', '10-11', '11-12','12-13','13-14','14-15','15-16','16-17','17-18','18-19','19-20','20-21','21-22'))
);


create role stuent_role;
GRANT select on Ressource TO student_role;
GRANT select,insert,delete on Demandes TO student_role;         
grant student_role to user_student;


create role admin_role;
GRANT ALL PRIVILEGES TO admin_role
GRANT select,update,insert,delete on my_users TO user_admin
GRANT select,insert,update,delete on Ressource TO user_admin
GRANT select,update,insert,delete on Demandes TO user_admin
grant admin_role to user_admin;


SET SERVEROUTPUT ON 
SPOOL admin_log_file.log SELECT * FROM v$session where username='user_admin';
SPOOL OFF

SET SERVEROUTPUT ON 
SPOOL student_log_file.log SELECT * FROM v$session where username='user_student';         
SPOOL OFF

